dist: focal
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9
- 3.10
before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends python3-dev libxml2-dev libxslt1-dev
  libxslt-dev libyajl2
- pip install -U pip setuptools wheel importlib-metadata
- pip install -r requirements-dev.txt
install: pip install -e .
script: py.test -vv --cov-report term-missing:skip-covered --cov=linkpreview
after_success: if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install coveralls; coveralls; fi
deploy:
  provider: pypi
  user: __token__
  password:
    secure: OD2zp2Mo5zSfUQ7lLYE+W87R99fr6g7iUyF6VSmcmqj3gEsIYvzGY40hpKpqZ+smlZ1vI/ni8ie09oWdef4bUI90YROXquuZN7vZ3wwu/3u+09SgdjJHNANl5WI9JPACgkfJeUt8qC5LySehe2ZSiLaUuWwocPn1FwT/6dtJ18jwO3WS76LfzQ4cVJthyIpMfMeF7Q4YTaMcx+5dVoktO3P5uo63PvMCBleek2tQPFjmfgzugHeSd5FR0pDOMeoax01Ov6XMn5/Ec2b4dcho0cMJmmthkmM/0dEfnTsW7vzFELFMqxm+69yx44Ez85WmnN0vCH3OqP/acs7JZtef3YbH+ccu1NrQIoDzL7KXp3P50r0OOrfoya0pQLvc95v//To1obknhkZsTw/gdNEVTzAC3mA1+7IbZvazAi77vyVdZtK9qd9Ro6/MrP9ZkS6ehOHeY5sPefh6VWXnbL0oQg8viChzwOrAN/nvXE3mXAiB8k+TCu/Gk52bjAsvxgH5W+IR9fPAKyHR4cbUsVK9FUXx8A45wkBjQWp7O2/uwKpFmwdGuXOu4SqOiO2vs0ox6es1oEu+b53+9waWV+0NXLeb0VlEraOuMVR2WlKaZ8baz6/mraKJB8C60NCle5W93TQOLJQSZ8578OGpOh41tWA5XRQB/bG30baSECNhSFA=
  on:
    python: 3.8
    tags: true
    distributions: sdist bdist_wheel
  skip-cleanup: true
  skip_existing: true
